---
title: "CodeBook"
author: "Frank Muntinga"
date: "Sunday, January 25, 2015"
output: html_document
---
### Definitions

## Activity

1. Activity.id        		Identifier of the Activity which was measured
2. Activity			Description of the actvity which was measured

ID 1 =	WALKING
ID 2 =	WALKING_UPSTAIRS
ID 3 = 	WALKING_DOWNSTAIRS
ID 4 = 	SITTING
ID 5 = 	STANDING
ID 6 = 	LAYING

## Subject

1. Subject 		Identifier of the person from whom's mobile phone data was collected during the test of train measurements.

## Measurements
 
 1. BodyAcc.mean...X 		Mean value body accelerometer raw time signals X-axis in g/sec
 2. BodyAcc.mean...Y 		Mean value body accelerometer raw time signals Y-axis in g/sec
 3. BodyAcc.mean...Z 		Mean value body accelerometer raw time signals Z-axis in g/sec
 4. GravityAcc.mean...X 	Mean value gravity accelerometer raw time signals X-axis in rad/sec
 5. GravityAcc.mean...Y         Mean value gravity accelerometer raw time signals Y-axis in rad/sec
 6. GravityAcc.mean...Z         Mean value gravity accelerometer raw time signals Z-axis in rad/sec
 7. BodyAccJerk.mean...X 	Mean value body accelerometer jerk time signals X-axis in g/sec
 8. BodyAccJerk.mean...Y 	Mean value body accelerometer jerk time signals X-axis in g/sec
 9. BodyAccJerk.mean...Z 	Mean value body accelerometer jerk time signals X-axis in g/sec
 10. BodyGyro.mean...X 		Mean value body gyroscope time signals X-axis in rad/sec
 11. BodyGyro.mean...Y 		Mean value body gyroscope time signals Y-axis in rad/sec
 12. BodyGyro.mean...Z 		Mean value body gyroscope time signals Z-axis in rad/sec
 13. BodyGyroJerk.mean...X 	Mean value body gyroscope jerk time signals X-axis in rad/sec
 14. BodyGyroJerk.mean...Y      Mean value body gyroscope jerk time signals Y-axis in rad/sec
 15. BodyGyroJerk.mean...Z      Mean value body gyroscope jerk time signals Z-axis in rad/sec
 16. BodyAccMag.mean.. 		Mean value body accelerometer magnitude of 3-dimensional time signals using Euclidian norm in g/sec
 17. GravityAccMag.mean.. 	Mean value gravity accelerometer magnitude of 3-dimensional time signals using Euclidian norm in g/sec
 18. BodyAccJerkMag.mean.. 	Mean value body accelerometer magnitude of 3-dimensional jerk time signals using Euclidian norm	in g/sec	
 19. BodyGyroMag.mean.. 	Mean value body gyroscope magnitude of 3-dimensional time signals using Euclidian norm in rad/sec
 20. BodyGyroJerkMag.mean.. 	Mean value body gyroscope magnitude of 3-dimensional jerk time signals using Euclidian norm in rad/sec
 21. BodyAcc.mean...X.1 	Mean value body accelerometer raw Fast Fourier Transform FFT signals X-axis in g/sec
 22. BodyAcc.mean...Y.1         Mean value body accelerometer raw Fast Fourier Transform FFT. signals Y-axis in g/sec
 23. BodyAcc.mean...Z.1         Mean value body accelerometer raw Fast Fourier Transform FFT. signals Z-axis in g/sec
 24. BodyAcc.meanFreq...X 	Mean fequency body accelerometer raw FFT signals X-axis in g/sec
 25. BodyAcc.meanFreq...Y 	Mean fequency body accelerometer raw FFT signals Y-axis in g/sec
 26. BodyAcc.meanFreq...Z 	Mean fequency body accelerometer raw FFT signals Z-axis in g/sec
 27. BodyAccJerk.mean...X.1 	Mean value body accelerometer jerk FFT signals X-axis in g/sec
 28. BodyAccJerk.mean...Y.1     Mean value body accelerometer jerk FFT signals X-axis in g/sec
 29. BodyAccJerk.mean...Z.1     Mean value body accelerometer jerk FFT signals X-axis in g/sec
 30. BodyAccJerk.meanFreq...X 	Mean fequency body accelerometer raw jerk FFT signals X-axis in g/sec
 31. BodyAccJerk.meanFreq...Y   Mean fequency body accelerometer raw jerk FFT signals Y-axis in g/sec
 32. BodyAccJerk.meanFreq...Z   Mean fequency body accelerometer raw jerk FFT signals Z-axis in g/sec
 33. BodyGyro.mean...X.1 	Mean value body gyroscope FFT signals X-axis in rad/sec
 34. BodyGyro.mean...Y.1        Mean value body gyroscope FFT signals Y-axis in rad/sec
 35. BodyGyro.mean...Z.1        Mean value body gyroscope FFT signals Z-axis in rad/sec
 36. BodyGyro.meanFreq...X 	Mean fequency body gyroscope raw FFT signals X-axis in rad/sec
 37. BodyGyro.meanFreq...Y      Mean fequency body gyroscope raw FFT signals Y-axis in rad/sec
 38. BodyGyro.meanFreq...Z      Mean fequency body gyroscope raw FFT signals Z-axis in rad/sec
 39. BodyAccMag.mean...1 	Mean value body accelerometer magnitude of 3-dimensional FFT signals using Euclidian norm in g/sec
 40. BodyAccMag.meanFreq.. 	Mean frequency body accelerometer magnitude of 3-dimensional FFT signals using Euclidian norm in g/sec
 41. BodyBodyAccJerkMag.mean.. 	Mean value body accelerometer magnitude of 3-dimensional jerk FFT signals using Euclidian norm in g/sec
 42. BodyBodyAccJerkMag.meanFreq.. Mean frequency body accelerometer magnitude of 3-dimensional jerk FFT signals using Euclidian norm in g/sec
 43. BodyBodyGyroMag.mean.. 	Mean value body gyroscope magnitude of 3-dimensional FFT signals using Euclidian norm in rad/sec
 44. BodyBodyGyroMag.meanFreq.. Mean frequency body gyroscope magnitude of 3-dimensional FFT signals using Euclidian norm in rad/sec
 45. BodyBodyGyroJerkMag.mean.. Mean value body gyroscope magnitude of 3-dimensional jerk FFT signals using Euclidian norm in rad/sec
 46. BodyBodyGyroJerkMag.meanFreq. Mean frequency body gyroscope magnitude of 3-dimensional jerk FFT signals using Euclidian norm in rad/sec 
 47. BodyAcc.std...X 		Standard deviation body accelerometer raw time signals X-axis in g/sec
 48. BodyAcc.std...Y            Standard deviation body accelerometer raw time signals Y-axis in g/sec
 49. BodyAcc.std...Z            Standard deviation body accelerometer raw time signals Z-axis in g/sec
 50. GravityAcc.std...X 	Standard deviation gravity accelerometer raw time signals X-axis in g/sec
 51. GravityAcc.std...Y         Standard deviation accelerometer raw time signals Y-axis in g/sec
 52. GravityAcc.std...Z         Standard deviation accelerometer raw time signals Z-axis in g/sec
 53. BodyAccJerk.std...X 	Standard deviation accelerometer jerk time signals X-axis in g/sec
 54. BodyAccJerk.std...Y        Standard deviation accelerometer jerk time signals X-axis in g/sec
 55. BodyAccJerk.std...Z        Standard deviation accelerometer jerk time signals X-axis in g/sec
 56. BodyGyro.std...X           Standard deviation gyroscope time signals X-axis in rad/sec
 57. BodyGyro.std...Y           Standard deviation gyroscope time signals Y-axis in rad/sec
 58. BodyGyro.std...Z           Standard deviation gyroscope time signals Z-axis in rad/sec
 59. BodyGyroJerk.std...X 	Standard deviation body gyroscope jerk time signals X-axis in rad/sec
 60. BodyGyroJerk.std...Y       Standard deviation body gyroscope jerk time signals Y-axis in rad/sec
 61. BodyGyroJerk.std...Z       Standard deviation body gyroscope jerk time signals Z-axis in rad/sec
 62. BodyAccMag.std.. 		Standard deviation body accelerometer magnitude of 3-dimensional time signals using Euclidian norm in g/sec
 63. GravityAccMag.std..        Standard deviation gravity accelerometer magnitude of 3-dimensional time signals using Euclidian in g/sec norm
 64. BodyAccJerkMag.std..       Standard deviation body accelerometer magnitude of 3-dimensional jerk time signals using Euclidian in g/sec norm		
 65. BodyGyroMag.std..          Standard deviation body gyroscope magnitude of 3-dimensional time signals using Euclidian norm in rad/sec
 66. BodyGyroJerkMag.std..      Standard deviation body gyroscope magnitude of 3-dimensional jerk time signals using Euclidian norm in rad/sec
 67. BodyAcc.std...X.1 		Standard deviation body accelerometer raw FFT signals X-axis in g/sec
 68. BodyAcc.std...Y.1          Standard deviation body accelerometer raw FFT signals Y-axis in g/sec
 69. BodyAcc.std...Z.1          Standard deviation body accelerometer raw FFT signals Z-axis in g/sec
 70. BodyAccJerk.std...X.1  	Standard deviation body accelerometer raw jerk FFT signals X-axis in g/sec
 71. BodyAccJerk.std...Y.1      Standard deviation body accelerometer raw jerk FFT signals Y-axis in g/sec
 72. BodyAccJerk.std...Z.1      Standard deviation body accelerometer raw jerk FFT signals Z-axis in g/sec
 73. BodyGyro.std...X.1 	Standard deviation gyroscope FFT signals X-axis in rad/sec
 74. BodyGyro.std...Y.1         Standard deviation gyroscope FFT signals Y-axis  in rad/sec
 75. BodyGyro.std...Z.1         Standard deviation gyroscope FFT signals Z-axis in rad/sec
 76. BodyAccMag.std...1 	Standard deviation body accelerometer magnitude of 3-dimensional FFT signals using Euclidian norm in g/sec
 77. BodyBodyAccJerkMag.std.. 	Standard deviation body accelerometer magnitude of 3-dimensional jerk FFT signals using Euclidian norm in g/sec	    78. BodyBodyGyroMag.std..       Standard deviation body gyroscope magnitude of 3-dimensional FFT signals using Euclidian norm in rad/sec
 79. BodyBodyGyroJerkMag.std.. 	Standard deviation body gyroscope magnitude of 3-dimensional jerk FFT signals using Euclidian norm in rad/sec	


### Transformations

* Get the data from the Web, unzip and store it in a working directory.
* Create dataframes for all the files needed in the analysis.
* Merge the training_x and the test_x sets to create one data set by using RBIND.
* Extract only the measurements on the mean and standard deviation for each measurement.
* Appropriately labels the data set with descriptive variable names.
* Merge the combined traing-test_x set to the subjects by using CBIND and modify lables to proper ones.
* Join the activity-labels by using a MERGE and modify lables to proper ones.
* Install package dplyr
* Create a summarized dataset by creating group-variable on activity&subject and use SUMMARISE_EACH with function MEAN 
  to apply this  grouping to the input-datafame and create a new tidy dataset.
* Write the tidy dataset (output) as well as the original dataset (input) to a local file.